version: 2.1

setup: true

orbs: 
  path-filtering: circleci/path-filtering@0.1.2

workflows:
  main:
    jobs:
      - path-filtering/filter:
          name: 'Check packages for changes'
          base-revision: main
          config-path: .circleci/continue-config.yml
          mapping: |
            packages/web-app-1/.* web-app-1 true
            packages/web-app-2/.* web-app-1 true
