import type { NextPage } from 'next'
import Head from 'next/head'
import { faker } from '@faker-js/faker';
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const [customer, setCustomer] = useState<acme.Customer>()

  useEffect(() => {
    const customer : acme.Customer = {
      first_name: faker.name.firstName(),
      last_name: faker.name.lastName(),
      email_address: faker.internet.email(),
      age: 33,
    }

    setCustomer(customer);
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Web App 2 - Acme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {customer && (
          <h1 className={styles.title}>
            Welcome, {customer.first_name}!
          </h1>
        )}
      </main>
    </div>
  )
}

export default Home
